In [1]:

import preprocessing1st as pre1
import preprocessing_nth as prenth
import modeling_score as mdsc
import lgbgrid as lgb_grid
# 1st preprocessing
pre = pre1.Preprocessing1st("../MACH_data/data.csv")
xy = pre.preprocessing_model()


# Nth preprocessing
nth = prenth.PreprocessingNth()

# feature_selection
fs = nth.feature_selection(*xy)

# feature_addition
fa = nth.feature_addition(*fs)

#gridsearchcv_lgb


# Modeling & Result
md = mdsc.Modeling(*fa)
md.print_score()
md.models_score_df()


AdaBoostClassifier()
confusion matrix
[[3030 2549]
 [1563 4524]]
Accuracy: 0.6475, AUC: 0.6432
Recall: 0.7432, f1_score: 0.6875, precision: 0.6396
GradientBoostingClassifier()
confusion matrix
[[3016 2563]
 [1495 4592]]
Accuracy: 0.6475, AUC: 0.6432
Recall: 0.7432, f1_score: 0.6875, precision: 0.6396
XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints='',
              learning_rate=0.300000012, max_delta_step=0, max_depth=6,
              min_child_weight=1, missing=nan, monotone_constraints='()',
              n_estimators=100, n_jobs=0, num_parallel_tree=1, random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, subsample=1,
              tree_method='exact', validate_parameters=1, verbosity=None)
confusion matrix
[[3219 2360]
 [1733 4354]]
Accuracy: 0.6475, AUC: 0.6432
Recall: 0.7432, f1_score: 0.6875, precisio

In [5]:
grid=lgb_grid.GridSearch(*fa)
lgb_grid_model = grid.model_load()

In [6]:
lgb_grid_model

LGBMClassifier(colsample_bytree=0.6, gamma=0.5, max_depth=10,
               min_child_weight=10, rabdom_state=13, subsample=0.6)

In [20]:
%%writefile gridsearchfinal.py
import modeling_score as mdsc
import numpy as np
import pandas as pd
from sklearn.metrics import (accuracy_score, precision_score, recall_score, 
                             f1_score, roc_auc_score, confusion_matrix, classification_report)
from sklearn.preprocessing import RobustScaler
from sklearn.model_selection import (train_test_split, cross_val_score, StratifiedKFold ,GridSearchCV)
from sklearn.ensemble import AdaBoostClassifier, GradientBoostingClassifier
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
import warnings
warnings.filterwarnings('ignore')

class Modeling2(mdsc.Modeling):
    def __init__(self, *xy_train_test, lgrid):
        ada = AdaBoostClassifier()
        gbc = GradientBoostingClassifier()
        xgb = XGBClassifier()
        lgbm = LGBMClassifier()
        self.grid_lgb= lgrid
        self.datas = []
        self.models = [ada, gbc, xgb, lgbm, self.grid_lgb]
        self.model_names = ['Ada', 'GBC', 'XGB', 'LGBM', "grid_lgb"]
        
        self.X_train, self.X_test, self.y_train, self.y_test = xy_train_test
        


Overwriting gridsearchfinal.py


In [16]:
fff = Modeling2(*fa, lgrid=lgb_grid_model)

In [17]:
fff.models_score_df()

          accuracy       AUC  precision    recall        f1
Ada       0.647523  0.643166   0.639615  0.743223  0.687538
GBC       0.652152  0.647497   0.641789  0.754395  0.693551
XGB       0.649151  0.646140   0.648496  0.715295  0.680259
LGBM      0.658409  0.654488   0.650962  0.744538  0.694613
grid_lgb  0.658066  0.654428   0.652338  0.737966  0.692515


In [ ]:
mdsc.Modeling(*fa)